[Interface]
Address = 10.8.1.3/32
PrivateKey = 8Ng3/zlhsOMZBKKt1D7NxaMdzIa20tM6NYg4a1UHQGk=
DNS = 1.1.1.1, 1.0.0.1
MTU = 1280
Jc = 4
Jmin = 10
Jmax = 50
S1 = 140
S2 = 17
S3 = 42
S4 = 12
H1 = 1
H2 = 2
H3 = 3
H4 = 4
HeaderProtectionKey = J/cxH8x/n3FWkBJNAQ1eN3I2gAiVzSqlO9ewFfRHOoY=
ContentPaddingAddition = 10-100
RekeyAfterTime = 100-120
RekeyTimeout = 3-7
RejectAfterTime = 150-180
KeepaliveTimeout = 5-15
MaxHandshakeAttempts = 15-20
RandomTrailers = on
DisableCookies = on

[Peer]
PublicKey = Ykpm/wNlGFXsl8R2GUeuaO5TMS4Lvyp1wV1aYO27S3g=
PresharedKey = gIE4lVGbbGwooerLC2ehJGasBEJA9grQ9lSUv1fkW/g=
AllowedIPs = 0.0.0.0/0
Endpoint = 65.109.212.237:39900
PersistentKeepalive = 25
